### ISSUE TITLE
Compilation is not always successful - remove dist folder

### ISSUE THREAD

**Issue by irelandm** [nearform/mira#100]
**Describe the bug**
Typescript compilation is not always successful. It is not obvious why, but removing the `dist` folder before compiling stops this being a problem. 

**To Reproduce**
Reproduction of this error is not consistent. It sometimes manifests as unexpected results when having made changes and after compiling using `npm run build`.
It might be possible to observe the `dist` folder and identify what causes this to happen but it is not worth the effort.

**Expected behavior**
Consistent compilation every time.

**Additional context**
Prevent this problem happening by changing `npm run build` to remove the `dist` folder (if it exists) before compiling

**Comment by mikegwhit** [comment]
Can pick this one up

**Comment by mikegwhit** [comment]
See https://github.com/nearform/mira/pull/103
