### ISSUE TITLE
Mira CICD doesn't update the permissions

### ISSUE THREAD

**Issue by irelandm** [nearform/mira#131]
**Describe the bug**
Once the CICD permissions are deployed, it is not possible to update them using `mira cicd`

**To Reproduce**
1. Deploy a CICD with some permissions
2. Change the permissions
3. Redeploy
4. Verify that the new permissions are not added

**Expected behavior**
The permissions should be updated

**Comment by irelandm** [comment]
Raised by Davide

**Comment by codeflyer** [comment]
I did some additional test, and it's actually updating the permission correctly. I was probably missing something. Probably the forgot to update the tsc compiler.
