### ISSUE TITLE
Accept Typescript files instead of Javascript

### ISSUE THREAD

**Issue by irelandm** [nearform/mira#16]
**Is your feature request related to a problem? Please describe.**
All the code is written in typescript but the entry point has to be specified as javascript file

**Describe the solution you'd like**
Change all requirements for .js files in the app to be .ts instead

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by leorossi** [comment]
There are two possible approaches

- use the [Compiler Api](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API) which is _not_ stable, but it would be cleaner
- run `tsc` with `child_process.exec` which is the way we run CDK, and, I guess, it would be easier and more stable.

Any thoughts @zimny ?
