### ISSUE TITLE
Generate API Docs

### ISSUE THREAD

**Issue by irelandm** [nearform/mira#39]
**Is your feature request related to a problem? Please describe.**
It can be hard to see the scope of the Mira API and the elements involved without API docs.

**Describe the solution you'd like**
We should publish the TSDoc comments to a browsable format.
We will use https://typedoc.org/ to generate this documentation, e.g. `typedoc --out docs --name 'src'`.
We can't use the current `docs` root as per this example though, due to the existing content. Therefore, ideally we need to find a way to include the API docs within that tree and thereby have the api docs included in the docset on netlify.

**Describe alternatives you've considered**
See #36.
If it is not possible to include the API docs in the main doc set then we should take a quick look at alternative tools.
If all else fails then we should just make it easy for the developer to generate the api docs locally.

**Additional context**
This follows on from issue #36 , to add appropriate comments to the code

**Comment by nigelhanlon** [comment]
Pull request https://github.com/nearform/mira/pull/74 adds autogenerated documentation to Mira via Typedoc.
