### ISSUE TITLE
Ensure Domain is optional

### ISSUE THREAD

**Issue by irelandm** [nearform/mira#4]
There is a report that having a custom domain is required to get CI running. This should not be the case, so change CI to make sure it is only optional.

Also verify that having a custom domain is optional for personal dev environments.

**Comment by codeflyer** [comment]
I've run a pipeline without the domain and works fine. Do you have more information about this issue?

**Comment by irelandm** [comment]
No, this was anecdotal. If you have checked and tested this, then we can close the issue.
