### ISSUE TITLE
NODE_ENV Warning 

### ISSUE THREAD

**Issue by irelandm** [nearform/mira#86]
**Describe the bug**
The following warning is given on `npm run deploy`
>WARNING: NODE_ENV value of 'dev' did not match any deployment config file names.

**To Reproduce**
1. Make a repo from the S3 web hosting sample, or otherwise start a new Mira project
2. npm install
3. npm run build
4. npm run deploy
5. See warning (this does not stop the deploy)

**Expected behavior**
The warning should not appear

**Screenshots**
![Screenshot 2020-09-07 at 12 03 45](https://user-images.githubusercontent.com/16843292/92392226-da761380-f115-11ea-86dc-7ffb20203f5b.png)

**Additional context**
Adding a `dev.json` file next to `default.json` did not appear to remove the warning - this should be investiagted

**Comment by nigelhanlon** [comment]
Creating a `dev.json` file in the config directory with a minimum of `{ }` in the file will remove the warning. There should be a way to do this via env flags to the node-config module but I was not able to get that working correctly. The S3 sample has been updated with a `dev.json` file and I can confirm the warning has disappeared.
 
![image](https://user-images.githubusercontent.com/5331111/92758819-02b87900-f387-11ea-9684-a1e5c889786f.png)

**Comment by irelandm** [comment]
Not sure how best to deal with this - it's a feature of the library and is a correct warning.
Maybe add a step to the Mira CLI to ask if you want to create it. Low priority, so closing for now.
