### ISSUE TITLE
Windows tests are broken

### ISSUE THREAD

**Issue by mikegwhit** [nearform/mira#95]
**Describe the bug**
On Windows, tests currently fail.

**To Reproduce**
1. Run `npm test` in the Mira repo.

**Expected behavior**
Tests pass

**Screenshots**
![image](https://user-images.githubusercontent.com/2973130/92687946-a9563880-f2f9-11ea-9241-a6b5e07233f0.png)
![image](https://user-images.githubusercontent.com/2973130/92687983-bd9a3580-f2f9-11ea-89c8-8de296c8e32c.png)
![image](https://user-images.githubusercontent.com/2973130/92688036-d7d41380-f2f9-11ea-9546-ee78231c1e29.png)
![image](https://user-images.githubusercontent.com/2973130/92688067-e6bac600-f2f9-11ea-8bd2-817004756913.png)

**Client (please complete the following information if relevant):**
 - Windows

**Comment by mikegwhit** [comment]
Addressed here: https://github.com/nearform/mira/pull/97

**Comment by irelandm** [comment]
Fixed by #97
